# Generated by Django 3.2.8 on 2021-10-13 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('product_name', models.CharField(max_length=128)),
                ('product_url', models.URLField(max_length=1024)),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream_id', models.CharField(max_length=128)),
                ('playback_id', models.CharField(max_length=128)),
                ('stream_key', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
